### ISSUE TITLE
password

### ISSUE THREAD

**Issue by wan65496** [EnriqueMoran/remoteTelegramShell#2]
Did everything as in the tutorial, except didn't know what should be put into the password in the config.txt.
After executing python3 telegramShellBot.py
got errors
  File "telegramShellBot.py", line 470
    bot.send_message(doc.chat.id, f"File saved as {file_path}")
I figured maybe it's because of the password setting. So this password is password of what??? Thanks.

**Comment by EnriqueMoran** [comment]
A password you choose, so only those who know it can use the bot.
It will be asked to new users (non registered in usersFile), only if they send the correct password, will be able to send commands.
